# inspired by https://github.com/conan-io/conan-docker-tools/blob/master/gcc_9/Dockerfile

FROM trassiross/conan-base

RUN sudo apt-get -qy install --no-install-recommends \
# needed to run 32bit toolchain binaries from sdkARM
        zlib1g:i386 \
        libstdc++6:i386

COPY config/ /home/conan/conan-config-from-repo
RUN conan config install ~/conan-config-from-repo \
    && conan remote add artifactory http://jenkins.dssl.local:8888/artifactory/api/conan/local-conan \
    && conan remote add artifactory-cache-bintray-trassir http://jenkins.dssl.local:8888/artifactory/api/conan/bintray-trassir
