name: Build Ubuntu 12.04 Docker image

on:
  push:
    branches:
      - master
      - gcc8
    paths:
      - 'toolchains/Dockerfile'
      - 'config/**'
      - '.github/workflows/build-toolchain-docker.yml'
  pull_request:
    paths:
      - 'toolchains/Dockerfile'
      - 'config/**'
      - '.github/workflows/build-toolchain-docker.yml'

jobs:
  build-toolchain-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker login
        run: |
          docker login -p ${{secrets.DOCKER_PASSWORD}} -u ${{secrets.DOCKER_USERNAME}}
      - name: Build docker image
        run: |
          docker build . -f toolchains/Dockerfile -t "trassiross/conan-gcc8"
      - name: Upload docker image
        run: |
          docker push "trassiross/conan-gcc8"
